<?xml version="1.0" encoding="utf-8"?><Database Name="TG_fatec" Class="DataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Usuario" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="CPF" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DataNascimento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Telefone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="Senha" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CEP" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Cidade" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="UF" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Logradouro" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Numero" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Bairro" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Complemento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TipoUsuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Usuario_Cliente" Member="Clientes" ThisKey="Id" OtherKey="IdUsuario" Type="Cliente" />
      <Association Name="Usuario_Entregador" Member="Entregadors" ThisKey="Id" OtherKey="IdUsuario" Type="Entregador" />
      <Association Name="Usuario_Produtor" Member="Produtors" ThisKey="Id" OtherKey="IdUsuario" Type="Produtor" />
    </Type>
  </Table>
  <Table Name="dbo.Cliente" Member="Clientes">
    <Type Name="Cliente">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AceitaReceberEmails" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AceitaReceberSMS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Cliente_Pedido" Member="Pedidos" ThisKey="Id" OtherKey="IdCliente" Type="Pedido" />
      <Association Name="Usuario_Cliente" Member="Usuario" ThisKey="IdUsuario" OtherKey="Id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Entrega" Member="Entregas">
    <Type Name="Entrega">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPedido" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdEntregador" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Saida" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PrevisaoEntrega" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Entrega" Member="Entrega1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Distancia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ValorEntrega" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Troco" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ValorTroco" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Cartao" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Entrega_Avaliacao" Member="Avaliacaos" ThisKey="Id" OtherKey="IdEntrega" Type="Avaliacao" />
      <Association Name="Entregador_Entrega" Member="Entregador" ThisKey="IdEntregador" OtherKey="Id" Type="Entregador" IsForeignKey="true" />
      <Association Name="Pedido_Entrega" Member="Pedido" ThisKey="IdPedido" OtherKey="Id" Type="Pedido" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Entregador" Member="Entregadors">
    <Type Name="Entregador">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumeroRegistroCNH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DataEmissaoCNH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="OrgaoEmissorCNH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UFCNH" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="CategoriaCNH" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="ModeloVeiculo" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="MarcaVeiculo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AnoVeiculo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CorVeiculo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PlacaVeiculo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Entregador_Entrega" Member="Entregas" ThisKey="Id" OtherKey="IdEntregador" Type="Entrega" />
      <Association Name="Usuario_Entregador" Member="Usuario" ThisKey="IdUsuario" OtherKey="Id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ItensPedido" Member="ItensPedidos">
    <Type Name="ItensPedido">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdProduto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPedido" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataCadastro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Pedido_ItensPedido" Member="Pedido" ThisKey="IdPedido" OtherKey="Id" Type="Pedido" IsForeignKey="true" />
      <Association Name="Produto_ItensPedido" Member="Produto" ThisKey="IdProduto" OtherKey="Id" Type="Produto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pedido" Member="Pedidos">
    <Type Name="Pedido">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdCliente" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataPedido" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ValorPedido" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TipoEntrega" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QuantidadeItens" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Pedido_Entrega" Member="Entregas" ThisKey="Id" OtherKey="IdPedido" Type="Entrega" />
      <Association Name="Pedido_ItensPedido" Member="ItensPedidos" ThisKey="Id" OtherKey="IdPedido" Type="ItensPedido" />
      <Association Name="Cliente_Pedido" Member="Cliente" ThisKey="IdCliente" OtherKey="Id" Type="Cliente" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Produto" Member="Produtos">
    <Type Name="Produto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quantidade" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Valor" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Descricao" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="UnidadeMedida" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Medida" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="Produto_ItensPedido" Member="ItensPedidos" ThisKey="Id" OtherKey="IdProduto" Type="ItensPedido" />
      <Association Name="Produto_ProdutosProdutor" Member="ProdutosProdutors" ThisKey="Id" OtherKey="IdProduto" Type="ProdutosProdutor" />
    </Type>
  </Table>
  <Table Name="dbo.Produtor" Member="Produtors">
    <Type Name="Produtor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AceitaCartao" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AceitaPix" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RealizaEntregas" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EnderecoProducao" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="CertificadoOrganico" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="Produtor_ProdutosProdutor" Member="ProdutosProdutors" ThisKey="Id" OtherKey="IdProdutor" Type="ProdutosProdutor" />
      <Association Name="Usuario_Produtor" Member="Usuario" ThisKey="IdUsuario" OtherKey="Id" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProdutosProdutor" Member="ProdutosProdutors">
    <Type Name="ProdutosProdutor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdProdutor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdProduto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataCadastro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Produto_ProdutosProdutor" Member="Produto" ThisKey="IdProduto" OtherKey="Id" Type="Produto" IsForeignKey="true" />
      <Association Name="Produtor_ProdutosProdutor" Member="Produtor" ThisKey="IdProdutor" OtherKey="Id" Type="Produtor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Avaliacao" Member="Avaliacaos">
    <Type Name="Avaliacao">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdEntrega" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Estrelas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Association Name="Entrega_Avaliacao" Member="Entrega" ThisKey="IdEntrega" OtherKey="Id" Type="Entrega" IsForeignKey="true" />
    </Type>
  </Table>
</Database>