#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TGOrganicos.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TG_fatec")]
	public partial class DataLinq : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertAvaliacao(Avaliacao instance);
    partial void UpdateAvaliacao(Avaliacao instance);
    partial void DeleteAvaliacao(Avaliacao instance);
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertEntrega(Entrega instance);
    partial void UpdateEntrega(Entrega instance);
    partial void DeleteEntrega(Entrega instance);
    partial void InsertItensPedido(ItensPedido instance);
    partial void UpdateItensPedido(ItensPedido instance);
    partial void DeleteItensPedido(ItensPedido instance);
    partial void InsertPedido(Pedido instance);
    partial void UpdatePedido(Pedido instance);
    partial void DeletePedido(Pedido instance);
    partial void InsertProduto(Produto instance);
    partial void UpdateProduto(Produto instance);
    partial void DeleteProduto(Produto instance);
    partial void InsertProdutor(Produtor instance);
    partial void UpdateProdutor(Produtor instance);
    partial void DeleteProdutor(Produtor instance);
    partial void InsertProdutosProdutor(ProdutosProdutor instance);
    partial void UpdateProdutosProdutor(ProdutosProdutor instance);
    partial void DeleteProdutosProdutor(ProdutosProdutor instance);
    #endregion
		
		public DataLinq(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinq(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinq(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinq(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Avaliacao> Avaliacaos
		{
			get
			{
				return this.GetTable<Avaliacao>();
			}
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Entrega> Entregas
		{
			get
			{
				return this.GetTable<Entrega>();
			}
		}
		
		public System.Data.Linq.Table<ItensPedido> ItensPedidos
		{
			get
			{
				return this.GetTable<ItensPedido>();
			}
		}
		
		public System.Data.Linq.Table<Pedido> Pedidos
		{
			get
			{
				return this.GetTable<Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Produto> Produtos
		{
			get
			{
				return this.GetTable<Produto>();
			}
		}
		
		public System.Data.Linq.Table<Produtor> Produtors
		{
			get
			{
				return this.GetTable<Produtor>();
			}
		}
		
		public System.Data.Linq.Table<ProdutosProdutor> ProdutosProdutors
		{
			get
			{
				return this.GetTable<ProdutosProdutor>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nome;
		
		private string _CPF;
		
		private System.Nullable<System.DateTime> _DataNascimento;
		
		private string _Telefone;
		
		private string _Email;
		
		private string _Senha;
		
		private string _CEP;
		
		private string _Cidade;
		
		private string _Estado;
		
		private string _UF;
		
		private string _Logradouro;
		
		private string _Numero;
		
		private string _Bairro;
		
		private string _Complemento;
		
		private System.Nullable<int> _TipoUsuario;
		
		private EntitySet<Cliente> _Clientes;
		
		private EntitySet<Produtor> _Produtors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnDataNascimentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataNascimentoChanged();
    partial void OnTelefoneChanging(string value);
    partial void OnTelefoneChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSenhaChanging(string value);
    partial void OnSenhaChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnLogradouroChanging(string value);
    partial void OnLogradouroChanged();
    partial void OnNumeroChanging(string value);
    partial void OnNumeroChanged();
    partial void OnBairroChanging(string value);
    partial void OnBairroChanged();
    partial void OnComplementoChanging(string value);
    partial void OnComplementoChanged();
    partial void OnTipoUsuarioChanging(System.Nullable<int> value);
    partial void OnTipoUsuarioChanged();
    #endregion
		
		public Usuario()
		{
			this._Clientes = new EntitySet<Cliente>(new Action<Cliente>(this.attach_Clientes), new Action<Cliente>(this.detach_Clientes));
			this._Produtors = new EntitySet<Produtor>(new Action<Produtor>(this.attach_Produtors), new Action<Produtor>(this.detach_Produtors));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(250)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(50)")]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataNascimento", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataNascimento
		{
			get
			{
				return this._DataNascimento;
			}
			set
			{
				if ((this._DataNascimento != value))
				{
					this.OnDataNascimentoChanging(value);
					this.SendPropertyChanging();
					this._DataNascimento = value;
					this.SendPropertyChanged("DataNascimento");
					this.OnDataNascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefone", DbType="VarChar(50)")]
		public string Telefone
		{
			get
			{
				return this._Telefone;
			}
			set
			{
				if ((this._Telefone != value))
				{
					this.OnTelefoneChanging(value);
					this.SendPropertyChanging();
					this._Telefone = value;
					this.SendPropertyChanged("Telefone");
					this.OnTelefoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(70)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Senha", DbType="VarChar(50)")]
		public string Senha
		{
			get
			{
				return this._Senha;
			}
			set
			{
				if ((this._Senha != value))
				{
					this.OnSenhaChanging(value);
					this.SendPropertyChanging();
					this._Senha = value;
					this.SendPropertyChanged("Senha");
					this.OnSenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="VarChar(10)")]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(100)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(2)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logradouro", DbType="VarChar(500)")]
		public string Logradouro
		{
			get
			{
				return this._Logradouro;
			}
			set
			{
				if ((this._Logradouro != value))
				{
					this.OnLogradouroChanging(value);
					this.SendPropertyChanging();
					this._Logradouro = value;
					this.SendPropertyChanged("Logradouro");
					this.OnLogradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="VarChar(10)")]
		public string Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro", DbType="VarChar(50)")]
		public string Bairro
		{
			get
			{
				return this._Bairro;
			}
			set
			{
				if ((this._Bairro != value))
				{
					this.OnBairroChanging(value);
					this.SendPropertyChanging();
					this._Bairro = value;
					this.SendPropertyChanged("Bairro");
					this.OnBairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Complemento", DbType="VarChar(50)")]
		public string Complemento
		{
			get
			{
				return this._Complemento;
			}
			set
			{
				if ((this._Complemento != value))
				{
					this.OnComplementoChanging(value);
					this.SendPropertyChanging();
					this._Complemento = value;
					this.SendPropertyChanged("Complemento");
					this.OnComplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoUsuario", DbType="Int")]
		public System.Nullable<int> TipoUsuario
		{
			get
			{
				return this._TipoUsuario;
			}
			set
			{
				if ((this._TipoUsuario != value))
				{
					this.OnTipoUsuarioChanging(value);
					this.SendPropertyChanging();
					this._TipoUsuario = value;
					this.SendPropertyChanged("TipoUsuario");
					this.OnTipoUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Cliente", Storage="_Clientes", ThisKey="Id", OtherKey="IdUsuario")]
		public EntitySet<Cliente> Clientes
		{
			get
			{
				return this._Clientes;
			}
			set
			{
				this._Clientes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Produtor", Storage="_Produtors", ThisKey="Id", OtherKey="IdUsuario")]
		public EntitySet<Produtor> Produtors
		{
			get
			{
				return this._Produtors;
			}
			set
			{
				this._Produtors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Clientes(Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Clientes(Cliente entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
		
		private void attach_Produtors(Produtor entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Produtors(Produtor entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Avaliacao")]
	public partial class Avaliacao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdEntrega;
		
		private System.Nullable<int> _Estrelas;
		
		private string _Comentario;
		
		private EntityRef<Entrega> _Entrega;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdEntregaChanging(int value);
    partial void OnIdEntregaChanged();
    partial void OnEstrelasChanging(System.Nullable<int> value);
    partial void OnEstrelasChanged();
    partial void OnComentarioChanging(string value);
    partial void OnComentarioChanged();
    #endregion
		
		public Avaliacao()
		{
			this._Entrega = default(EntityRef<Entrega>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEntrega", DbType="Int NOT NULL")]
		public int IdEntrega
		{
			get
			{
				return this._IdEntrega;
			}
			set
			{
				if ((this._IdEntrega != value))
				{
					if (this._Entrega.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdEntregaChanging(value);
					this.SendPropertyChanging();
					this._IdEntrega = value;
					this.SendPropertyChanged("IdEntrega");
					this.OnIdEntregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estrelas", DbType="Int")]
		public System.Nullable<int> Estrelas
		{
			get
			{
				return this._Estrelas;
			}
			set
			{
				if ((this._Estrelas != value))
				{
					this.OnEstrelasChanging(value);
					this.SendPropertyChanging();
					this._Estrelas = value;
					this.SendPropertyChanged("Estrelas");
					this.OnEstrelasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comentario", DbType="VarChar(500)")]
		public string Comentario
		{
			get
			{
				return this._Comentario;
			}
			set
			{
				if ((this._Comentario != value))
				{
					this.OnComentarioChanging(value);
					this.SendPropertyChanging();
					this._Comentario = value;
					this.SendPropertyChanged("Comentario");
					this.OnComentarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Entrega_Avaliacao", Storage="_Entrega", ThisKey="IdEntrega", OtherKey="Id", IsForeignKey=true)]
		public Entrega Entrega
		{
			get
			{
				return this._Entrega.Entity;
			}
			set
			{
				Entrega previousValue = this._Entrega.Entity;
				if (((previousValue != value) 
							|| (this._Entrega.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Entrega.Entity = null;
						previousValue.Avaliacaos.Remove(this);
					}
					this._Entrega.Entity = value;
					if ((value != null))
					{
						value.Avaliacaos.Add(this);
						this._IdEntrega = value.Id;
					}
					else
					{
						this._IdEntrega = default(int);
					}
					this.SendPropertyChanged("Entrega");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdUsuario;
		
		private System.Nullable<bool> _AceitaReceberEmails;
		
		private System.Nullable<bool> _AceitaReceberSMS;
		
		private EntitySet<Pedido> _Pedidos;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnAceitaReceberEmailsChanging(System.Nullable<bool> value);
    partial void OnAceitaReceberEmailsChanged();
    partial void OnAceitaReceberSMSChanging(System.Nullable<bool> value);
    partial void OnAceitaReceberSMSChanged();
    #endregion
		
		public Cliente()
		{
			this._Pedidos = new EntitySet<Pedido>(new Action<Pedido>(this.attach_Pedidos), new Action<Pedido>(this.detach_Pedidos));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AceitaReceberEmails", DbType="Bit")]
		public System.Nullable<bool> AceitaReceberEmails
		{
			get
			{
				return this._AceitaReceberEmails;
			}
			set
			{
				if ((this._AceitaReceberEmails != value))
				{
					this.OnAceitaReceberEmailsChanging(value);
					this.SendPropertyChanging();
					this._AceitaReceberEmails = value;
					this.SendPropertyChanged("AceitaReceberEmails");
					this.OnAceitaReceberEmailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AceitaReceberSMS", DbType="Bit")]
		public System.Nullable<bool> AceitaReceberSMS
		{
			get
			{
				return this._AceitaReceberSMS;
			}
			set
			{
				if ((this._AceitaReceberSMS != value))
				{
					this.OnAceitaReceberSMSChanging(value);
					this.SendPropertyChanging();
					this._AceitaReceberSMS = value;
					this.SendPropertyChanged("AceitaReceberSMS");
					this.OnAceitaReceberSMSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Pedido", Storage="_Pedidos", ThisKey="Id", OtherKey="IdCliente")]
		public EntitySet<Pedido> Pedidos
		{
			get
			{
				return this._Pedidos;
			}
			set
			{
				this._Pedidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Cliente", Storage="_Usuario", ThisKey="IdUsuario", OtherKey="Id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Clientes.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Clientes.Add(this);
						this._IdUsuario = value.Id;
					}
					else
					{
						this._IdUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Pedidos(Pedido entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Entrega")]
	public partial class Entrega : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdPedido;
		
		private System.Nullable<System.DateTime> _Saida;
		
		private System.Nullable<System.DateTime> _PrevisaoEntrega;
		
		private System.Nullable<System.DateTime> _Entrega1;
		
		private System.Nullable<decimal> _Distancia;
		
		private System.Nullable<decimal> _ValorEntrega;
		
		private System.Nullable<bool> _Troco;
		
		private System.Nullable<decimal> _ValorTroco;
		
		private System.Nullable<bool> _Cartao;
		
		private EntitySet<Avaliacao> _Avaliacaos;
		
		private EntityRef<Pedido> _Pedido;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdPedidoChanging(int value);
    partial void OnIdPedidoChanged();
    partial void OnSaidaChanging(System.Nullable<System.DateTime> value);
    partial void OnSaidaChanged();
    partial void OnPrevisaoEntregaChanging(System.Nullable<System.DateTime> value);
    partial void OnPrevisaoEntregaChanged();
    partial void OnEntrega1Changing(System.Nullable<System.DateTime> value);
    partial void OnEntrega1Changed();
    partial void OnDistanciaChanging(System.Nullable<decimal> value);
    partial void OnDistanciaChanged();
    partial void OnValorEntregaChanging(System.Nullable<decimal> value);
    partial void OnValorEntregaChanged();
    partial void OnTrocoChanging(System.Nullable<bool> value);
    partial void OnTrocoChanged();
    partial void OnValorTrocoChanging(System.Nullable<decimal> value);
    partial void OnValorTrocoChanged();
    partial void OnCartaoChanging(System.Nullable<bool> value);
    partial void OnCartaoChanged();
    #endregion
		
		public Entrega()
		{
			this._Avaliacaos = new EntitySet<Avaliacao>(new Action<Avaliacao>(this.attach_Avaliacaos), new Action<Avaliacao>(this.detach_Avaliacaos));
			this._Pedido = default(EntityRef<Pedido>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPedido", DbType="Int NOT NULL")]
		public int IdPedido
		{
			get
			{
				return this._IdPedido;
			}
			set
			{
				if ((this._IdPedido != value))
				{
					if (this._Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPedidoChanging(value);
					this.SendPropertyChanging();
					this._IdPedido = value;
					this.SendPropertyChanged("IdPedido");
					this.OnIdPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saida", DbType="DateTime")]
		public System.Nullable<System.DateTime> Saida
		{
			get
			{
				return this._Saida;
			}
			set
			{
				if ((this._Saida != value))
				{
					this.OnSaidaChanging(value);
					this.SendPropertyChanging();
					this._Saida = value;
					this.SendPropertyChanged("Saida");
					this.OnSaidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrevisaoEntrega", DbType="DateTime")]
		public System.Nullable<System.DateTime> PrevisaoEntrega
		{
			get
			{
				return this._PrevisaoEntrega;
			}
			set
			{
				if ((this._PrevisaoEntrega != value))
				{
					this.OnPrevisaoEntregaChanging(value);
					this.SendPropertyChanging();
					this._PrevisaoEntrega = value;
					this.SendPropertyChanged("PrevisaoEntrega");
					this.OnPrevisaoEntregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Entrega", Storage="_Entrega1", DbType="DateTime")]
		public System.Nullable<System.DateTime> Entrega1
		{
			get
			{
				return this._Entrega1;
			}
			set
			{
				if ((this._Entrega1 != value))
				{
					this.OnEntrega1Changing(value);
					this.SendPropertyChanging();
					this._Entrega1 = value;
					this.SendPropertyChanged("Entrega1");
					this.OnEntrega1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Distancia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Distancia
		{
			get
			{
				return this._Distancia;
			}
			set
			{
				if ((this._Distancia != value))
				{
					this.OnDistanciaChanging(value);
					this.SendPropertyChanging();
					this._Distancia = value;
					this.SendPropertyChanged("Distancia");
					this.OnDistanciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorEntrega", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ValorEntrega
		{
			get
			{
				return this._ValorEntrega;
			}
			set
			{
				if ((this._ValorEntrega != value))
				{
					this.OnValorEntregaChanging(value);
					this.SendPropertyChanging();
					this._ValorEntrega = value;
					this.SendPropertyChanged("ValorEntrega");
					this.OnValorEntregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Troco", DbType="Bit")]
		public System.Nullable<bool> Troco
		{
			get
			{
				return this._Troco;
			}
			set
			{
				if ((this._Troco != value))
				{
					this.OnTrocoChanging(value);
					this.SendPropertyChanging();
					this._Troco = value;
					this.SendPropertyChanged("Troco");
					this.OnTrocoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorTroco", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ValorTroco
		{
			get
			{
				return this._ValorTroco;
			}
			set
			{
				if ((this._ValorTroco != value))
				{
					this.OnValorTrocoChanging(value);
					this.SendPropertyChanging();
					this._ValorTroco = value;
					this.SendPropertyChanged("ValorTroco");
					this.OnValorTrocoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cartao", DbType="Bit")]
		public System.Nullable<bool> Cartao
		{
			get
			{
				return this._Cartao;
			}
			set
			{
				if ((this._Cartao != value))
				{
					this.OnCartaoChanging(value);
					this.SendPropertyChanging();
					this._Cartao = value;
					this.SendPropertyChanged("Cartao");
					this.OnCartaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Entrega_Avaliacao", Storage="_Avaliacaos", ThisKey="Id", OtherKey="IdEntrega")]
		public EntitySet<Avaliacao> Avaliacaos
		{
			get
			{
				return this._Avaliacaos;
			}
			set
			{
				this._Avaliacaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Entrega", Storage="_Pedido", ThisKey="IdPedido", OtherKey="Id", IsForeignKey=true)]
		public Pedido Pedido
		{
			get
			{
				return this._Pedido.Entity;
			}
			set
			{
				Pedido previousValue = this._Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pedido.Entity = null;
						previousValue.Entregas.Remove(this);
					}
					this._Pedido.Entity = value;
					if ((value != null))
					{
						value.Entregas.Add(this);
						this._IdPedido = value.Id;
					}
					else
					{
						this._IdPedido = default(int);
					}
					this.SendPropertyChanged("Pedido");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Avaliacaos(Avaliacao entity)
		{
			this.SendPropertyChanging();
			entity.Entrega = this;
		}
		
		private void detach_Avaliacaos(Avaliacao entity)
		{
			this.SendPropertyChanging();
			entity.Entrega = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ItensPedido")]
	public partial class ItensPedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdProduto;
		
		private int _IdPedido;
		
		private System.Nullable<System.DateTime> _DataCadastro;
		
		private System.Nullable<decimal> _Valor;
		
		private System.Nullable<decimal> _Quantidade;
		
		private string _Status;
		
		private EntityRef<Pedido> _Pedido;
		
		private EntityRef<Produto> _Produto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdProdutoChanging(int value);
    partial void OnIdProdutoChanged();
    partial void OnIdPedidoChanging(int value);
    partial void OnIdPedidoChanged();
    partial void OnDataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OnDataCadastroChanged();
    partial void OnValorChanging(System.Nullable<decimal> value);
    partial void OnValorChanged();
    partial void OnQuantidadeChanging(System.Nullable<decimal> value);
    partial void OnQuantidadeChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public ItensPedido()
		{
			this._Pedido = default(EntityRef<Pedido>);
			this._Produto = default(EntityRef<Produto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProduto", DbType="Int NOT NULL")]
		public int IdProduto
		{
			get
			{
				return this._IdProduto;
			}
			set
			{
				if ((this._IdProduto != value))
				{
					if (this._Produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProdutoChanging(value);
					this.SendPropertyChanging();
					this._IdProduto = value;
					this.SendPropertyChanged("IdProduto");
					this.OnIdProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPedido", DbType="Int NOT NULL")]
		public int IdPedido
		{
			get
			{
				return this._IdPedido;
			}
			set
			{
				if ((this._IdPedido != value))
				{
					if (this._Pedido.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdPedidoChanging(value);
					this.SendPropertyChanging();
					this._IdPedido = value;
					this.SendPropertyChanged("IdPedido");
					this.OnIdPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCadastro", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataCadastro
		{
			get
			{
				return this._DataCadastro;
			}
			set
			{
				if ((this._DataCadastro != value))
				{
					this.OnDataCadastroChanging(value);
					this.SendPropertyChanging();
					this._DataCadastro = value;
					this.SendPropertyChanged("DataCadastro");
					this.OnDataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantidade", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Quantidade
		{
			get
			{
				return this._Quantidade;
			}
			set
			{
				if ((this._Quantidade != value))
				{
					this.OnQuantidadeChanging(value);
					this.SendPropertyChanging();
					this._Quantidade = value;
					this.SendPropertyChanged("Quantidade");
					this.OnQuantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(15)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_ItensPedido", Storage="_Pedido", ThisKey="IdPedido", OtherKey="Id", IsForeignKey=true)]
		public Pedido Pedido
		{
			get
			{
				return this._Pedido.Entity;
			}
			set
			{
				Pedido previousValue = this._Pedido.Entity;
				if (((previousValue != value) 
							|| (this._Pedido.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Pedido.Entity = null;
						previousValue.ItensPedidos.Remove(this);
					}
					this._Pedido.Entity = value;
					if ((value != null))
					{
						value.ItensPedidos.Add(this);
						this._IdPedido = value.Id;
					}
					else
					{
						this._IdPedido = default(int);
					}
					this.SendPropertyChanged("Pedido");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_ItensPedido", Storage="_Produto", ThisKey="IdProduto", OtherKey="Id", IsForeignKey=true)]
		public Produto Produto
		{
			get
			{
				return this._Produto.Entity;
			}
			set
			{
				Produto previousValue = this._Produto.Entity;
				if (((previousValue != value) 
							|| (this._Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produto.Entity = null;
						previousValue.ItensPedidos.Remove(this);
					}
					this._Produto.Entity = value;
					if ((value != null))
					{
						value.ItensPedidos.Add(this);
						this._IdProduto = value.Id;
					}
					else
					{
						this._IdProduto = default(int);
					}
					this.SendPropertyChanged("Produto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pedido")]
	public partial class Pedido : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdCliente;
		
		private System.Nullable<System.DateTime> _DataPedido;
		
		private string _TipoEntrega;
		
		private System.Nullable<decimal> _ValorPedido;
		
		private System.Nullable<decimal> _QuantidadeItens;
		
		private string _Status;
		
		private EntitySet<Entrega> _Entregas;
		
		private EntitySet<ItensPedido> _ItensPedidos;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdClienteChanging(int value);
    partial void OnIdClienteChanged();
    partial void OnDataPedidoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataPedidoChanged();
    partial void OnTipoEntregaChanging(string value);
    partial void OnTipoEntregaChanged();
    partial void OnValorPedidoChanging(System.Nullable<decimal> value);
    partial void OnValorPedidoChanged();
    partial void OnQuantidadeItensChanging(System.Nullable<decimal> value);
    partial void OnQuantidadeItensChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public Pedido()
		{
			this._Entregas = new EntitySet<Entrega>(new Action<Entrega>(this.attach_Entregas), new Action<Entrega>(this.detach_Entregas));
			this._ItensPedidos = new EntitySet<ItensPedido>(new Action<ItensPedido>(this.attach_ItensPedidos), new Action<ItensPedido>(this.detach_ItensPedidos));
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCliente", DbType="Int NOT NULL")]
		public int IdCliente
		{
			get
			{
				return this._IdCliente;
			}
			set
			{
				if ((this._IdCliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdClienteChanging(value);
					this.SendPropertyChanging();
					this._IdCliente = value;
					this.SendPropertyChanged("IdCliente");
					this.OnIdClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataPedido", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataPedido
		{
			get
			{
				return this._DataPedido;
			}
			set
			{
				if ((this._DataPedido != value))
				{
					this.OnDataPedidoChanging(value);
					this.SendPropertyChanging();
					this._DataPedido = value;
					this.SendPropertyChanged("DataPedido");
					this.OnDataPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoEntrega", DbType="VarChar(50)")]
		public string TipoEntrega
		{
			get
			{
				return this._TipoEntrega;
			}
			set
			{
				if ((this._TipoEntrega != value))
				{
					this.OnTipoEntregaChanging(value);
					this.SendPropertyChanging();
					this._TipoEntrega = value;
					this.SendPropertyChanged("TipoEntrega");
					this.OnTipoEntregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValorPedido", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ValorPedido
		{
			get
			{
				return this._ValorPedido;
			}
			set
			{
				if ((this._ValorPedido != value))
				{
					this.OnValorPedidoChanging(value);
					this.SendPropertyChanging();
					this._ValorPedido = value;
					this.SendPropertyChanged("ValorPedido");
					this.OnValorPedidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuantidadeItens", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> QuantidadeItens
		{
			get
			{
				return this._QuantidadeItens;
			}
			set
			{
				if ((this._QuantidadeItens != value))
				{
					this.OnQuantidadeItensChanging(value);
					this.SendPropertyChanging();
					this._QuantidadeItens = value;
					this.SendPropertyChanged("QuantidadeItens");
					this.OnQuantidadeItensChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(15)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_Entrega", Storage="_Entregas", ThisKey="Id", OtherKey="IdPedido")]
		public EntitySet<Entrega> Entregas
		{
			get
			{
				return this._Entregas;
			}
			set
			{
				this._Entregas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Pedido_ItensPedido", Storage="_ItensPedidos", ThisKey="Id", OtherKey="IdPedido")]
		public EntitySet<ItensPedido> ItensPedidos
		{
			get
			{
				return this._ItensPedidos;
			}
			set
			{
				this._ItensPedidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Pedido", Storage="_Cliente", ThisKey="IdCliente", OtherKey="Id", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Pedidos.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Pedidos.Add(this);
						this._IdCliente = value.Id;
					}
					else
					{
						this._IdCliente = default(int);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Entregas(Entrega entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = this;
		}
		
		private void detach_Entregas(Entrega entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = null;
		}
		
		private void attach_ItensPedidos(ItensPedido entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = this;
		}
		
		private void detach_ItensPedidos(ItensPedido entity)
		{
			this.SendPropertyChanging();
			entity.Pedido = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produto")]
	public partial class Produto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Nome;
		
		private System.Nullable<decimal> _Quantidade;
		
		private System.Nullable<decimal> _Valor;
		
		private string _Descricao;
		
		private string _UnidadeMedida;
		
		private System.Nullable<decimal> _Medida;
		
		private string _Imagem;
		
		private System.Nullable<int> _TipoProduto;
		
		private EntitySet<ItensPedido> _ItensPedidos;
		
		private EntitySet<ProdutosProdutor> _ProdutosProdutors;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnQuantidadeChanging(System.Nullable<decimal> value);
    partial void OnQuantidadeChanged();
    partial void OnValorChanging(System.Nullable<decimal> value);
    partial void OnValorChanged();
    partial void OnDescricaoChanging(string value);
    partial void OnDescricaoChanged();
    partial void OnUnidadeMedidaChanging(string value);
    partial void OnUnidadeMedidaChanged();
    partial void OnMedidaChanging(System.Nullable<decimal> value);
    partial void OnMedidaChanged();
    partial void OnImagemChanging(string value);
    partial void OnImagemChanged();
    partial void OnTipoProdutoChanging(System.Nullable<int> value);
    partial void OnTipoProdutoChanged();
    #endregion
		
		public Produto()
		{
			this._ItensPedidos = new EntitySet<ItensPedido>(new Action<ItensPedido>(this.attach_ItensPedidos), new Action<ItensPedido>(this.detach_ItensPedidos));
			this._ProdutosProdutors = new EntitySet<ProdutosProdutor>(new Action<ProdutosProdutor>(this.attach_ProdutosProdutors), new Action<ProdutosProdutor>(this.detach_ProdutosProdutors));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantidade", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Quantidade
		{
			get
			{
				return this._Quantidade;
			}
			set
			{
				if ((this._Quantidade != value))
				{
					this.OnQuantidadeChanging(value);
					this.SendPropertyChanging();
					this._Quantidade = value;
					this.SendPropertyChanged("Quantidade");
					this.OnQuantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descricao", DbType="VarChar(500)")]
		public string Descricao
		{
			get
			{
				return this._Descricao;
			}
			set
			{
				if ((this._Descricao != value))
				{
					this.OnDescricaoChanging(value);
					this.SendPropertyChanging();
					this._Descricao = value;
					this.SendPropertyChanged("Descricao");
					this.OnDescricaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadeMedida", DbType="VarChar(50)")]
		public string UnidadeMedida
		{
			get
			{
				return this._UnidadeMedida;
			}
			set
			{
				if ((this._UnidadeMedida != value))
				{
					this.OnUnidadeMedidaChanging(value);
					this.SendPropertyChanging();
					this._UnidadeMedida = value;
					this.SendPropertyChanged("UnidadeMedida");
					this.OnUnidadeMedidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Medida", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Medida
		{
			get
			{
				return this._Medida;
			}
			set
			{
				if ((this._Medida != value))
				{
					this.OnMedidaChanging(value);
					this.SendPropertyChanging();
					this._Medida = value;
					this.SendPropertyChanged("Medida");
					this.OnMedidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagem", DbType="VarChar(5000)")]
		public string Imagem
		{
			get
			{
				return this._Imagem;
			}
			set
			{
				if ((this._Imagem != value))
				{
					this.OnImagemChanging(value);
					this.SendPropertyChanging();
					this._Imagem = value;
					this.SendPropertyChanged("Imagem");
					this.OnImagemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoProduto", DbType="Int")]
		public System.Nullable<int> TipoProduto
		{
			get
			{
				return this._TipoProduto;
			}
			set
			{
				if ((this._TipoProduto != value))
				{
					this.OnTipoProdutoChanging(value);
					this.SendPropertyChanging();
					this._TipoProduto = value;
					this.SendPropertyChanged("TipoProduto");
					this.OnTipoProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_ItensPedido", Storage="_ItensPedidos", ThisKey="Id", OtherKey="IdProduto")]
		public EntitySet<ItensPedido> ItensPedidos
		{
			get
			{
				return this._ItensPedidos;
			}
			set
			{
				this._ItensPedidos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_ProdutosProdutor", Storage="_ProdutosProdutors", ThisKey="Id", OtherKey="IdProduto")]
		public EntitySet<ProdutosProdutor> ProdutosProdutors
		{
			get
			{
				return this._ProdutosProdutors;
			}
			set
			{
				this._ProdutosProdutors.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ItensPedidos(ItensPedido entity)
		{
			this.SendPropertyChanging();
			entity.Produto = this;
		}
		
		private void detach_ItensPedidos(ItensPedido entity)
		{
			this.SendPropertyChanging();
			entity.Produto = null;
		}
		
		private void attach_ProdutosProdutors(ProdutosProdutor entity)
		{
			this.SendPropertyChanging();
			entity.Produto = this;
		}
		
		private void detach_ProdutosProdutors(ProdutosProdutor entity)
		{
			this.SendPropertyChanging();
			entity.Produto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Produtor")]
	public partial class Produtor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdUsuario;
		
		private System.Nullable<bool> _AceitaCartao;
		
		private System.Nullable<bool> _AceitaPix;
		
		private System.Nullable<bool> _RealizaEntregas;
		
		private string _EnderecoProducao;
		
		private string _CertificadoOrganico;
		
		private EntitySet<ProdutosProdutor> _ProdutosProdutors;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnAceitaCartaoChanging(System.Nullable<bool> value);
    partial void OnAceitaCartaoChanged();
    partial void OnAceitaPixChanging(System.Nullable<bool> value);
    partial void OnAceitaPixChanged();
    partial void OnRealizaEntregasChanging(System.Nullable<bool> value);
    partial void OnRealizaEntregasChanged();
    partial void OnEnderecoProducaoChanging(string value);
    partial void OnEnderecoProducaoChanged();
    partial void OnCertificadoOrganicoChanging(string value);
    partial void OnCertificadoOrganicoChanged();
    #endregion
		
		public Produtor()
		{
			this._ProdutosProdutors = new EntitySet<ProdutosProdutor>(new Action<ProdutosProdutor>(this.attach_ProdutosProdutors), new Action<ProdutosProdutor>(this.detach_ProdutosProdutors));
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="Int NOT NULL")]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AceitaCartao", DbType="Bit")]
		public System.Nullable<bool> AceitaCartao
		{
			get
			{
				return this._AceitaCartao;
			}
			set
			{
				if ((this._AceitaCartao != value))
				{
					this.OnAceitaCartaoChanging(value);
					this.SendPropertyChanging();
					this._AceitaCartao = value;
					this.SendPropertyChanged("AceitaCartao");
					this.OnAceitaCartaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AceitaPix", DbType="Bit")]
		public System.Nullable<bool> AceitaPix
		{
			get
			{
				return this._AceitaPix;
			}
			set
			{
				if ((this._AceitaPix != value))
				{
					this.OnAceitaPixChanging(value);
					this.SendPropertyChanging();
					this._AceitaPix = value;
					this.SendPropertyChanged("AceitaPix");
					this.OnAceitaPixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealizaEntregas", DbType="Bit")]
		public System.Nullable<bool> RealizaEntregas
		{
			get
			{
				return this._RealizaEntregas;
			}
			set
			{
				if ((this._RealizaEntregas != value))
				{
					this.OnRealizaEntregasChanging(value);
					this.SendPropertyChanging();
					this._RealizaEntregas = value;
					this.SendPropertyChanged("RealizaEntregas");
					this.OnRealizaEntregasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnderecoProducao", DbType="VarChar(500)")]
		public string EnderecoProducao
		{
			get
			{
				return this._EnderecoProducao;
			}
			set
			{
				if ((this._EnderecoProducao != value))
				{
					this.OnEnderecoProducaoChanging(value);
					this.SendPropertyChanging();
					this._EnderecoProducao = value;
					this.SendPropertyChanged("EnderecoProducao");
					this.OnEnderecoProducaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CertificadoOrganico", DbType="VarChar(500)")]
		public string CertificadoOrganico
		{
			get
			{
				return this._CertificadoOrganico;
			}
			set
			{
				if ((this._CertificadoOrganico != value))
				{
					this.OnCertificadoOrganicoChanging(value);
					this.SendPropertyChanging();
					this._CertificadoOrganico = value;
					this.SendPropertyChanged("CertificadoOrganico");
					this.OnCertificadoOrganicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produtor_ProdutosProdutor", Storage="_ProdutosProdutors", ThisKey="Id", OtherKey="IdProdutor")]
		public EntitySet<ProdutosProdutor> ProdutosProdutors
		{
			get
			{
				return this._ProdutosProdutors;
			}
			set
			{
				this._ProdutosProdutors.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Produtor", Storage="_Usuario", ThisKey="IdUsuario", OtherKey="Id", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Produtors.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Produtors.Add(this);
						this._IdUsuario = value.Id;
					}
					else
					{
						this._IdUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ProdutosProdutors(ProdutosProdutor entity)
		{
			this.SendPropertyChanging();
			entity.Produtor = this;
		}
		
		private void detach_ProdutosProdutors(ProdutosProdutor entity)
		{
			this.SendPropertyChanging();
			entity.Produtor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProdutosProdutor")]
	public partial class ProdutosProdutor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _IdProdutor;
		
		private int _IdProduto;
		
		private System.Nullable<System.DateTime> _DataCadastro;
		
		private EntityRef<Produto> _Produto;
		
		private EntityRef<Produtor> _Produtor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIdProdutorChanging(int value);
    partial void OnIdProdutorChanged();
    partial void OnIdProdutoChanging(int value);
    partial void OnIdProdutoChanged();
    partial void OnDataCadastroChanging(System.Nullable<System.DateTime> value);
    partial void OnDataCadastroChanged();
    #endregion
		
		public ProdutosProdutor()
		{
			this._Produto = default(EntityRef<Produto>);
			this._Produtor = default(EntityRef<Produtor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProdutor", DbType="Int NOT NULL")]
		public int IdProdutor
		{
			get
			{
				return this._IdProdutor;
			}
			set
			{
				if ((this._IdProdutor != value))
				{
					if (this._Produtor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProdutorChanging(value);
					this.SendPropertyChanging();
					this._IdProdutor = value;
					this.SendPropertyChanged("IdProdutor");
					this.OnIdProdutorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProduto", DbType="Int NOT NULL")]
		public int IdProduto
		{
			get
			{
				return this._IdProduto;
			}
			set
			{
				if ((this._IdProduto != value))
				{
					if (this._Produto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdProdutoChanging(value);
					this.SendPropertyChanging();
					this._IdProduto = value;
					this.SendPropertyChanged("IdProduto");
					this.OnIdProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCadastro", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataCadastro
		{
			get
			{
				return this._DataCadastro;
			}
			set
			{
				if ((this._DataCadastro != value))
				{
					this.OnDataCadastroChanging(value);
					this.SendPropertyChanging();
					this._DataCadastro = value;
					this.SendPropertyChanged("DataCadastro");
					this.OnDataCadastroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produto_ProdutosProdutor", Storage="_Produto", ThisKey="IdProduto", OtherKey="Id", IsForeignKey=true)]
		public Produto Produto
		{
			get
			{
				return this._Produto.Entity;
			}
			set
			{
				Produto previousValue = this._Produto.Entity;
				if (((previousValue != value) 
							|| (this._Produto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produto.Entity = null;
						previousValue.ProdutosProdutors.Remove(this);
					}
					this._Produto.Entity = value;
					if ((value != null))
					{
						value.ProdutosProdutors.Add(this);
						this._IdProduto = value.Id;
					}
					else
					{
						this._IdProduto = default(int);
					}
					this.SendPropertyChanged("Produto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Produtor_ProdutosProdutor", Storage="_Produtor", ThisKey="IdProdutor", OtherKey="Id", IsForeignKey=true)]
		public Produtor Produtor
		{
			get
			{
				return this._Produtor.Entity;
			}
			set
			{
				Produtor previousValue = this._Produtor.Entity;
				if (((previousValue != value) 
							|| (this._Produtor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Produtor.Entity = null;
						previousValue.ProdutosProdutors.Remove(this);
					}
					this._Produtor.Entity = value;
					if ((value != null))
					{
						value.ProdutosProdutors.Add(this);
						this._IdProdutor = value.Id;
					}
					else
					{
						this._IdProdutor = default(int);
					}
					this.SendPropertyChanged("Produtor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
